name: TTBUtils
main: org.TTB.TTBUtils.TTBUtils
version: 1.0
depend: [Vault]
commands:
  rankup:
   description: Pay to rankup on the server.
  pinfo:
   description: Show A Players Information
permissions:
  ttbutils.*:
    description: All TTBUTils Perms
    children:
      ttbutils.staff: true
      ttbutils.user: true
  ttbutils.staff:
    description: Permissions For Staff
    children:
      ttbutils.cmd.staff.clearinv: true
      ttbutils.cmd.staff.pinfo: true
      ttbutils.cmd.staff.kick: true
      ttbutils.cmd.staff.ipinfo: true
  ttbutils.user:
    description: Permissions For Users
    children:
      ttbutils.cmd.user.merchant: true
  ttbutils.cmd.user.merchant:
    description: Merchant Rankup Permission
  ttbutils.cmd.staff.clearinv:
    description: ClearInv Permission
  ttbutils.cmd.staff.pinfo:
    description: pinfo Permission
  ttbutils.cmd.staff.kick:
    description: Kick A Player
  ttbutils.cmd.staff.ipinfo:
    description: IPInfo Permission